CREATE TABLE url_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_url VARCHAR(2048) NOT NULL,
    short_code VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    hit_count INT DEFAULT 0,
    CONSTRAINT uq_original_url UNIQUE (original_url),
    CONSTRAINT uq_short_code UNIQUE (short_code)
);

CREATE TABLE access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accessed_at TIMESTAMP WITH TIME ZONE,
    ip_address VARCHAR(255),
    user_agent VARCHAR(1024),
    referrer VARCHAR(1024),
    url_mapping_id BIGINT NOT NULL,
    CONSTRAINT fk_url_mapping FOREIGN KEY (url_mapping_id) REFERENCES url_mapping(id)
);
